### PR TITLE
Updates README.md to use Markdown, and small grammar fixes

### PR DESCRIPTION
**Pull request by crweiner**
I wanted to take the time to format your README.md file to actually use Markdown so it is easier to read on Github. This PR also fixes some small grammar/spelling mistakes. 

Enjoy your pretty Readme and thanks for a great WordPress plugin! :smile:

### CODE REVIEW

**Comment by crweiner** [comment]
Also updates .travis.yml in order to get Travis to pass. PHP 5.3 needs to be on Precise. 
https://docs.travis-ci.com/user/reference/trusty#php-images

Should also consider testing with different/newer versions of PHP.

**Comment by nlemoine** [comment]
Hi @crweiner, 

Wow, thanks for this PR, as you can see, this repository is in sleep. I want to revamp it since a long time but can't find any time to do it. 

Meanwhile, this is a great addition. Thanks!

**Comment by nlemoine** [comment]
And sorry for my english 😉

**Comment by crweiner** [comment]
No problem at all! :smile: I wanted to help in the spirit of Hacktoberfest. Your English is great so don't worry. Thanks for the merge and good luck with your future projects!

**Pull request merged**
